version: 0.0

os: linux 

files:
  - source: /
    destination: /src
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh     
      timeout: 600
      runas: root